### PR TITLE
Check in more event templates for the pilot

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XTCgwBrif91LNecKw:-N9XTCgx2bt8AbtvoV5u:bm2363o) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
> ```protobuf
> 
>   // Zip code where the ad was viewed.
>   string zip_code = 1;
> ```

How about something more generic, like `location_id`? IMO if we call it `zip_code` then it would be a bit of an abuse to put something other than a ZIP code in this field. With `location_id`, the content could be anything that the MC-EDP pair has agreed on.

@stevenwarejones what do you think?
___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XZJUg3JC7ny2Jxtvc:-N9XZJUg3JC7ny2Jxtvd:b-ac61mt) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
> ```protobuf
> 
>   // Zip code where the ad was viewed.
>   string zip_code = 1;
> ```

This field should be wrapped in a message so that it can be annotated with the `event_field` option. Some things won't work properly without using these annotations, such as the `EventTemplate`'s ability to grab its fields dynamically [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5192b5f4f9a81daf6734d62d9183e9573610c30d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L38-L45).
___
*[`src/main/proto/event_templates/geo_template.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9X_8h0711_X_xxoqLm:-N9X_8h0711_X_xxoqLn:bp1gqym) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L33)):*
> ```protobuf
>   // Zip code where the ad was viewed.
>   string zip_code = 1;
> }
> ```

nit: Can you add a newline at the end of this file?
___
*[`src/main/proto/event_templates/platform_template.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9X_Ez10X47UnpGOBkh:-N9X_Ez10X47UnpGOBki:bv1ope6) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/platform_template.proto#L42)):*
> ```protobuf
>   }
>   // The platform on which the ad was viewed.
>   Platform platform = 6;
> ```

Same thing here: this should all be wrapped in a message and annotated with `event_field`, the same way you did it for `AgeRange` and `Gender`.



_Code quote:_
```protobuf
  // Platform on which an impression was viewed by a virtual person.
  enum Platform {
    // Not set intentionally
    PLATFORM_UNKNOWN = 0;
    PLATFORM_DESKTOP = 1;
    PLATFORM_MOBILE = 2;
    PLATFORM_TABLET = 3;
    PLATFORM_CASTED_TV = 4;
  }
  // The platform on which the ad was viewed.
  Platform platform = 6;
```
___
*[`src/main/proto/event_templates/platform_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9X_SmM0V3wbTXavUjQ:-N9X_SmM0V3wbTXavUjR:b-y9p0h0) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/platform_template.proto#L43)):*
> ```protobuf
>   // The platform on which the ad was viewed.
>   Platform platform = 6;
> }
> ```

nit: Same here (newline at end of file).

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XTCgwBrif91LNecKw:-N9YVNE_BTa2LXp-nbZM:b-uh8td7) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
>  the content could be anything that the MC-EDP pair has agreed on.
I really like the idea. thanks Stephen
___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XZJUg3JC7ny2Jxtvc:-N9YVQPD8Yt4ph5LQMLb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This field should be wrapped in a message so that it can be annotated with the `event_field` option. Some things won't work properly without using these annotations, such as the `EventTemplate`'s ability to grab its fields dynamically [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5192b5f4f9a81daf6734d62d9183e9573610c30d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplate.kt#L38-L45).
</blockquote></details>

Done.
___
*[`src/main/proto/event_templates/platform_template.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9X_Ez10X47UnpGOBkh:-N9YVRUz8PWUzkmsvqAW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/platform_template.proto#L42)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Same thing here: this should all be wrapped in a message and annotated with `event_field`, the same way you did it for `AgeRange` and `Gender`.
</blockquote></details>

Done.

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/proto/event_templates/geo_template.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9bIqsa4xM1Pui-Hj3C:-N9bIqsa4xM1Pui-Hj3D:bsw7mwv) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/7de5046e5355a024631430f88e681e2c23f1fef0/src/main/proto/event_templates/geo_template.proto#L36)):*
> ```protobuf
>     };
> 
>     // location id of where the ad was viewed. The content could be anything
> ```

nit: Please capitalize the first letter of the sentence: `l` -> `L`.
___
*[`src/main/proto/event_templates/platform_template.proto` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9bJDbg9TomFQWhVQ_4:-N9bJDbg9TomFQWhVQ_5:b-ldiyhx) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/7de5046e5355a024631430f88e681e2c23f1fef0/src/main/proto/event_templates/platform_template.proto#L28)):*
> ```protobuf
>     name: "base_demographics_template"
>     display_name: "Base Demographics"
>     description: "An Event Template that specifies age range and gender."
> ```

These three values need to be updated.



_Code quote:_
```protobuf
    name: "base_demographics_template"
    display_name: "Base Demographics"
    description: "An Event Template that specifies age range and gender."
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/proto/event_templates/platform_template.proto` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9bJDbg9TomFQWhVQ_4:-N9bLzFMAHx2ej6ibDJc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/7de5046e5355a024631430f88e681e2c23f1fef0/src/main/proto/event_templates/platform_template.proto#L28)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

These three values need to be updated.
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9bQ1qw9vUvhLwG-hhI:-N9bQ1qw9vUvhLwG-hhJ:bn9h2ul) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/c8d51de6d5375249757022e3205db2b03a120baa/src/main/proto/eventtemplates/base_demographics_template.proto#L37)):*
> ```protobuf
> 
>     enum Value {
>       AGE_GROUP_UNSPECIFIED = 0;
> ```

nit: `GROUP` -> `RANGE`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XTCgwBrif91LNecKw:-N9fyVnH0rini2A7fLgF:b6p7so5) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

>  the content could be anything that the MC-EDP pair has agreed on.
I really like the idea. thanks Stephen
</blockquote></details>

I think location_id works for single country measurements. GeoLocation includes country_id, region_id, and city_id https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7268767b7034bdf7ad4e5282cb892d0618cd1030/src/main/proto/wfa/virtual_people/common/geo_location.proto#L26 -- however, I don't think those are perfect either.

I think we could start with location_id for now. 
___
*[`src/main/proto/eventtemplates/platform_template.proto` line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9fz8up7pHSZv3dPu5r:-N9fz8up7pHSZv3dPu5s:b-8xctkj) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/a87744f6062933db6a7d688855088f2da9514075/src/main/proto/eventtemplates/platform_template.proto#L43)):*
> ```protobuf
>       PLATFORM_MOBILE = 2;
>       PLATFORM_TABLET = 3;
>       PLATFORM_CASTED_TV = 4;
> ```

why not just `PLATFORM_TV` ? meaning they watched on their TV.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/proto/event_templates/geo_template.proto` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9XTCgwBrif91LNecKw:-N9iqr395HB4NgSk7EeN:b-5j6b7b) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/93f35ae49a581aa2b9f284adef55310f984d0491/src/main/proto/event_templates/geo_template.proto#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think location_id works for single country measurements. GeoLocation includes country_id, region_id, and city_id https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7268767b7034bdf7ad4e5282cb892d0618cd1030/src/main/proto/wfa/virtual_people/common/geo_location.proto#L26 -- however, I don't think those are perfect either.

I think we could start with location_id for now. 
</blockquote></details>

ah thanks, ok lets start with this.
___
*[`src/main/proto/eventtemplates/platform_template.proto` line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3#-N9fz8up7pHSZv3dPu5r:-N9ir4coEc9JtxKPizsr:b-3sdqya) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/a87744f6062933db6a7d688855088f2da9514075/src/main/proto/eventtemplates/platform_template.proto#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just `PLATFORM_TV` ? meaning they watched on their TV. 
</blockquote></details>

sure. makes sense, updated.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
