### PR TITLE
Added missing age range to the demo template

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)

### CODE REVIEW

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-N9rmdoh8PHZJdj0J3pK:bcgx67d) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
> ```protobuf
>       AGE_45_TO_54 = 4;
>       AGE_55_TO_64 = 5;
>       AGE_OVER_64 = 6;
> ```

Should this be AGE_OVER_65 instead? Or AGE_65_PLUS, which is widely used.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wliue)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-N9rsPS-5OehjjyUDDwo:b-6d2d1j) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Should this be AGE_OVER_65 instead? Or AGE_65_PLUS, which is widely used.
</blockquote></details>

thanks, updated

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Comment by sandip80** [comment]
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-NBIoffa6Ghs9jqL-CaI:b8x45b2) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thanks, updated
</blockquote></details>

Can you please also add AGE_55_PLUS?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mpatel24 and @sandip80)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-NBJK0vZ1M4I7LoI8a38:b-5zhhb3) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

Can you please also add AGE_55_PLUS?
</blockquote></details>

We can do that but that will cover AGE_55_TO_64 and AGE_OVER_64 together.
Is there a reason we can't just use that combination if an MC wants to get AGE_55_PLUS?
These templates should be supported by all EDPs in the system so if an EDP is not able to support an enum here like AGE_55_PLUS, we need to make a note of that and also get alignment of what it means externally. I think there are 2 options to move forward : 
1) Leave it as is and use that combination of AGE_55_TO_64 and AGE_OVER_64 to cover AGE_55_PLUS
2) Start a thread on Slack cross-media-general channel with Jukka to put this new enum and understand what are the implications of sending AGE_55_TO_64 for example to an EDP that doesn't support it

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mpatel24 and @sandip80)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-NBJNLI48d-LtOoJ2IxT:b984ee2) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

We can do that but that will cover AGE_55_TO_64 and AGE_OVER_64 together.
Is there a reason we can't just use that combination if an MC wants to get AGE_55_PLUS?
These templates should be supported by all EDPs in the system so if an EDP is not able to support an enum here like AGE_55_PLUS, we need to make a note of that and also get alignment of what it means externally. I think there are 2 options to move forward : 
1) Leave it as is and use that combination of AGE_55_TO_64 and AGE_OVER_64 to cover AGE_55_PLUS
2) Start a thread on Slack cross-media-general channel with Jukka to put this new enum and understand what are the implications of sending AGE_55_TO_64 for example to an EDP that doesn't support it
</blockquote></details>

IMO the enum values here should cover mutually exclusive ranges. The filter predicate can easily specify that it wants more than one such range.

**Comment by sandip80** [comment]
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-NBJwGmpDzJhqBA4g4Bg:b-q0lop7) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IMO the enum values here should cover mutually exclusive ranges. The filter predicate can easily specify that it wants more than one such range.
</blockquote></details>

Got it. Thanks for the clarification. This looks good to me.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mpatel24 and @sandip80)

___
*[`src/main/proto/eventtemplates/base_demographics_template.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-N9rmdoh8PHZJdj0J3pJ:-NBO05YPBZ5OMjpzBLc0:b-daw709) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/08b146f35200b27d54cb0ae81efcb3bf2eb1f3ba/src/main/proto/eventtemplates/base_demographics_template.proto#L43)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

Got it. Thanks for the clarification. This looks good to me.
</blockquote></details>

awesome thank you. Can you also approve the PR please ? :)

**Review by sandip80 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4#-:-NBOGRYk-dWf1Un826rQ:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mpatel24)

**Review by uakyol — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mpatel24)

**Pull request merged**
