### PR TITLE
Setup repo

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[`AUTHORS` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zKj2x1KzjqPFBes-a:-N8zKj2x1KzjqPFBes-b:bgak31q) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/AUTHORS#L9)):*
> ```
> 
> Google LLC
> Facebook, Inc.
> ```

Meta Platforms, Inc.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: all files reviewed, 4 unresolved discussions (waiting on @uakyol)

___
*[`WORKSPACE` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zilMYCRHzfW-pJlsp:-N8zilMYCRHzfW-pJlsq:bnfitct) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/WORKSPACE#L1)):*
> ```Starlark
> workspace(name = "wfa_measurement_system")
> ```

This must be unique to each workspace. Here you've just copied the value from the cross-media-measurement repo.



_Code quote:_
```Starlark
wfa_measurement_system
```
___
*[`.github/workflows/build-test.yml` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8ziwZA5EfGzUbfuCaH:-N8ziwZA5EfGzUbfuCaI:b8udnaf) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/.github/workflows/build-test.yml#L28)):*
> ```YAML
>   build-test:
>     name: Build and test
>     runs-on: ubuntu-18.04
> ```

nit: new code should use 20.04



_Code quote:_
```YAML
18.04
```
___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zj4hAA8dUMN0EbVJy:-N8zj4hAA8dUMN0EbVJz:b50m86u) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/build/repositories.bzl#L22)):*
> ```Starlark
> 
> def wfa_measurement_system_repositories():
>     """Imports all direct dependencies for wfa_measurement_system."""
> ```

Same here: clean up to refer to this workspace



_Code quote:_
```Starlark
wfa_measurement_system
```

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`AUTHORS` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zKj2x1KzjqPFBes-a:-N92cBJR215XOeRiniKk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/AUTHORS#L9)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Meta Platforms, Inc.
</blockquote></details>

Done.
___
*[`WORKSPACE` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zilMYCRHzfW-pJlsp:-N92cCBG5NNWOcs3ASOB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/WORKSPACE#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This must be unique to each workspace. Here you've just copied the value from the cross-media-measurement repo.
</blockquote></details>

Done.
___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zj4hAA8dUMN0EbVJy:-N92c670EUKMigucxhh9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/build/repositories.bzl#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here: clean up to refer to this workspace
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zj4hAA8dUMN0EbVJy:-N92hQao7L4njmLIN20b:bfk8aue) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/build/repositories.bzl#L22)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fix the function name too.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`build/repositories.bzl` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1#-N8zj4hAA8dUMN0EbVJy:-N92jgnu1iZuSfF3JVLL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/us-pilot-event-templates/blob/9a37c0e35af711c33733ecc798cb825a83f01cfb/build/repositories.bzl#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fix the function name too.
</blockquote></details>

Done.

**Review by uakyol — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by uakyol — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/us-pilot-event-templates/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
